// Generated by CoffeeScript 1.12.3
(function() {
  $(function() {
    var mixer;
    $('.page-scroll').smoothScroll({
      offset: 0,
      speed: 800,
      afterScroll: function() {
        var $target;
        $target = $('.navbar-collapse');
        if ($target.hasClass('collapse show')) {
          return $target.collapse('hide');
        }
      }
    });
    if ($('#grid').length > 0) {
      return mixer = mixitup('#grid', {
        controls: {
          toggleLogic: 'and',
          enable: true
        },
        selectors: {
          target: '.grid-item'
        },
        animation: {
          duration: 250,
          nudge: false,
          reverseOut: false,
          effects: 'fade'
        },
        callbacks: {
          onMixFail: function(state) {
            console.log('No items could be found matching the requested filter');
            return $('#empty-list').collapse('show');
          },
          onMixEnd: function(state) {
            var $alert;
            $alert = $('#empty-list');
            if (state.totalShow > 0 && $alert.hasClass('show')) {
              return $alert.collapse('hide');
            }
          }
        }
      });
    }
  });

}).call(this);
